// src/lib/Nav.svelte
<script lang="ts">
  import Burger from "./Burger.svelte";
  import Logo from "./Logo.svelte";
  import classnames from "classnames";
  import { page } from "$app/stores";

  interface Props {
    children: any;
  }

  type NavItem = {
    href: string;
    name: string;
    label?: string;
    className?: string;
  };

  const navItems = ["about", "work", "notes", "contact"];

  const { children }: Props = $props();

  let path = $derived($page.url.pathname);

  let mobileMenuOpen = $state(false);
  const toggleMobileMenu = () => {
    mobileMenuOpen = !mobileMenuOpen;
  };
</script>

{#snippet navItem(item: NavItem)}
  <li class={classnames({ selected: path === item.href })}>
    <a aria-label={item.label} href={item.href}>{item.name}</a>
  </li>
{/snippet}

{#snippet menuItems(navItems: string[])}
  <ul class="nav-items">
    {#each navItems as item}
      {@render navItem({ href: `/${item}`, name: item })}
    {/each}
  </ul>
{/snippet}

<div>
  <header>
    <nav class={classnames({ ["mobile-menu-open"]: mobileMenuOpen })}>
      <div class="top-menu">
        <ul>
          <Logo selected={path === "/"} />
          <li class="desktop-menu">
            {@render menuItems(navItems)}
          </li>
        </ul>
        <Burger className="hamburger" onclick={toggleMobileMenu} open={mobileMenuOpen} />
      </div>
      <div class="mobile-menu">
        {@render menuItems(navItems)}
      </div>
    </nav>
  </header>
  <div class={classnames("content", { hidden: mobileMenuOpen })}>
    {#if children}
      {@render children()}
    {/if}
  </div>
</div>

<style lang="scss">
  .top-menu {
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: var(--color--bg--accent);
    border-bottom: rem(8px) solid var(--color--brand);
    height: rem(84px);
    font-size: rem(20px);
    padding-inline: rem(20px);
  }

  ul {
    display: flex;
    flex-flow: row nowrap;
    align-items: center;
    justify-content: space-between;
    list-style: none;
    width: 100%;
    max-width: var(--size--content--max);
  }

  :global(.hamburger) {
    display: block;
  }

  .mobile-menu {
    display: none;
  }

  .mobile-menu-open {
    .mobile-menu {
      display: block;
    }
  }

  .nav-items {
    flex-flow: column;
  }

  li {
    color: var(--color--accent);
    padding-inline-start: 0;
    padding-block: rem(28px);
    font-size: rem(32px);

    &.selected {
      color: var(--color--brand);
      @include nav-item-selected-decoration;
    }
  }

  a {
    color: inherit;
    text-decoration: none;
  }

  .desktop-menu {
    display: none;
  }

  .content {
    &.hidden {
      display: none;
    }
  }

  @media (min-width: 786px) {
    nav {
      height: initial;
    }

    :global(.hamburger),
    .mobile-menu,
    .mobile-menu.open {
      display: none;
    }

    .desktop-menu {
      display: block;
    }

    .mobile-menu {
      display: none !important;
    }

    .nav-items {
      display: flex;
      flex-flow: row nowrap;
      gap: rem(48px);
    }

    li {
      font-size: rem(20px);

      &:hover {
        color: var(--color--brand);
      }
    }
  }
</style>

// components/nav/index.tsx
import Link from "next/link";
import styled from "styled-components";
import { fontSize, headingFontFamily } from "../../styles/typography";
import { Container } from "../layout";
import { Logo } from "../logo";
import { NavItem } from "../navItem";

const Navbar = styled.nav`
  width: 100%;
  border-bottom: 3px solid ${(props) => props.theme.colors.primary};
  font-size: ${fontSize.heading[4]};
  background-color: ${(props) => props.theme.colors.background_accent};
`;

const NavItems = styled(Container)`
  height: 100%;
  display: flex;
  flex-flow: row;
  justify-content: space-between;
  align-items: center;
`;

const SiteLinks = styled.ul`
  list-style: none;
  display: flex;
  flex-flow: row nowrap;
  align-items: center;
  justify-content: space-between;
  margin: 0;
  padding: 0;
  flex-basis: 33%;

  li {
    margin: 0;
    font-family: ${headingFontFamily};

    &:last-child {
      padding-right: 0;
    }
  }
`;

const Nav: React.FC = ({ children }) => {
  return (
    <Navbar>
      <NavItems>
        <Logo />
        <SiteLinks>
          <li>
            <Link passHref href="/about">
              <a>
                <NavItem>about</NavItem>
              </a>
            </Link>
          </li>
          <li>
            <Link passHref href="/work">
              <a>
                <NavItem>work</NavItem>
              </a>
            </Link>
          </li>
          <li>
            <Link passHref href="/notes">
              <a>
                <NavItem>notes</NavItem>
              </a>
            </Link>
          </li>
          <li>
            <Link passHref href="/connect">
              <a>
                <NavItem>connect</NavItem>
              </a>
            </Link>
          </li>
        </SiteLinks>
      </NavItems>
    </Navbar>
  );
};

export { Nav };
